{"uid":"93fc68524fee7ffd","name":"An uncaught error was detected outside of a test","fullName":".An uncaught error was detected outside of a test","historyId":"52a12849550d3513996e41b83e83be38","time":{"start":1746077358771,"stop":1746077359380,"duration":609},"description":"","descriptionHtml":"","status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n                \n                  > process is not defined\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","statusTrace":"ReferenceError: The following error originated from your test code, not from Cypress.\n                \n                  > process is not defined\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.\n                    at ./node_modules/cypress/node_modules/ci-info/index.js (webpack://satest/./node_modules/cypress/node_modules/ci-info/index.js:5:0)\n                    at __webpack_require__ (webpack://satest/webpack/bootstrap:19:0)\n                    at ./node_modules/cypress/lib/util.js (webpack://satest/./node_modules/cypress/lib/util.js:12:13)\n                    at __webpack_require__ (webpack://satest/webpack/bootstrap:19:0)\n                    at ./node_modules/cypress/index.js (webpack://satest/./node_modules/cypress/index.js:6:13)\n                    at __webpack_require__ (webpack://satest/webpack/bootstrap:19:0)\n                    at eval (webpack://satest/./cypress/e2e/suggestionsDtd28022025.cy.js:1:16)\n                    at eval (http://localhost:54631/__cypress/tests?p=cypress\\e2e\\suggestionsDtd28022025.cy.js:155662:3)\n                    at eval (http://localhost:54631/__cypress/tests?p=cypress\\e2e\\suggestionsDtd28022025.cy.js:155664:12)\n                    at eval (<anonymous>)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"suite","value":""},{"name":"testClass","value":""},{"name":"testMethod","value":"An uncaught error was detected outside of a test"},{"name":"package","value":""},{"name":"resultFormat","value":"allure1"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"7dacf2f79bdbb534","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n                \n                  > process is not defined\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","time":{"start":1744965086141,"stop":1744965086740,"duration":599}},{"uid":"4c84edc06318a013","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n                \n                  > process is not defined\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","time":{"start":1744356179220,"stop":1744356179891,"duration":671}},{"uid":"2ac2d0791ab936c6","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n                \n                  > process is not defined\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","time":{"start":1744355292610,"stop":1744355292959,"duration":349}},{"uid":"36b9d39ec7fc7de1","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n                \n                  > process is not defined\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","time":{"start":1744183813349,"stop":1744183813949,"duration":600}},{"uid":"2456b2bf8b64f683","status":"broken","statusDetails":"The following error originated from your test code, not from Cypress.\n                \n                  > process is not defined\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.","time":{"start":1742191697533,"stop":1742191698289,"duration":756}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"93fc68524fee7ffd.json","parameterValues":[]}